export const usersActionTypes = {
    // Login
    AUTH_LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',


    // Ambil data Pengghuni
    GET_TENANTS_REQUEST: 'GET_TENANTS_REQUEST',
    GET_TENANTS_SUCCESS: 'GET_TENANTS_SUCCESS',
    GET_TENANTS_FAILURE: 'GET_TENANTS_FAILURE',

    // Delete penghuni
    DELETE_TENANTS_REQUEST: 'DELETE_TENANTS_REQUEST',
    DELETE_TENANTS_SUCCESS: 'DELETE_TENANTS_SUCCESS',
    DELETE_TENANTS_FAILURE: 'DELETE_TENANTS_FAILURE',

    // Tambah data penghuni
    CREATE_TENANTS_REQUEST: 'CREATE_TENANTS_REQUEST',
    CREATE_TENANTS_SUCCESS: 'CREATE_TENANTS_SUCCESS',
    CREATE_TENANTS_FAILURE: 'CREATE_TENANTS_FAILURE',
    
    // edit Pengghuni
    TENANTS_EDIT_REQUEST: 'TENANTS_EDIT_REQUEST',
    TENANTS_EDIT_SUCCESS: 'TENANTS_EDIT_SUCCESS',
    TENANTS_EDIT_FAILURE: 'TENANTS_EDIT_FAILURE',
    // respon edit
    TENANTS_EDIT_RESPONSE_REQUEST: 'TENANTS_EDIT_RESPONSE_REQUEST',
    TENANTS_EDIT_RESPONSE_SUCCESS: 'TENANTS_EDIT_RESPONSE_SUCCESS',
    TENANTS_EDIT_RESPONSE_FAILURE: 'TENANTS_EDIT_RESPONSE_FAILURE',

    // data kos
    GET_COSMOS_DATA_REQUEST: 'GET_COSMOS_DATA_REQUEST',
    GET_COSMOS_DATA_SUCCESS: 'GET_COSMOS_DATA_SUCCESS',
    GET_COSMOS_DATA_FAILURE: 'GET_COSMOS_DATA_FAILURE',

    // perbarui data kos
    UPDATE_COSMOS_DATA_REQUEST: 'UPDATE_COSMOS_DATA_REQUEST',
    UPDATE_COSMOS_DATA_SUCCESS: 'UPDATE_COSMOS_DATA_SUCCESS',
    UPDATE_COSMOS_DATA_FAILURE: 'UPDATE_COSMOS_DATA_FAILURE',

    // Tampil data keluhan
    GET_COMPLAIN_REQUEST: 'GET_COMPLAIN_REQUEST',
    GET_COMPLAIN_SUCCESS: 'GET_COMPLAIN_SUCCESS',
    GET_COMPLAIN_FAILURE: 'GET_COMPLAIN_FAILURE',

    // Logout
    AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
    AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
    AUTH_LOGOUT_FAILURE: 'AUTH_LOGOUT_FAILURE',
}